variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages: 
  - build
  - test
  - sonarqubeTest
  - sonarqube

build:
  stage: build 
  script:
    - cd ./Application/ChooseYourAdventure 
    - gradle assemble

test: 
  stage: test 
  script:
    - cd ./Application/ChooseYourAdventure
    - gradle test


sonarqube-test:
  stage: sonarqubeTest 
  script: 
    - cd ./Application/ChooseYourAdventure
    - gradle test jacocoTestReport

sonarqube-check:
  stage: sonarqube  
  script: 
    - cd ./Application/ChooseYourAdventure
    - gradle sonarqube

