variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages: 
  - build
  - test

build:
  stage: build 
  script:
    - cd ./Application/ChooseYourAdventure 
    - gradle assemble


sonarqube-check:
  stage: test  
  script: 
    - cd ./Application/ChooseYourAdventure
    - gradle sonarqube
  allow_failure: true
  only:
    - master # or the name of your main branch

