variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages: 
  - build
  - test

build:
  stage: build 
  script:
    - cd ../Application/ChooseYourAdventure 
    - gradle assemble

test: 
  stage: test 
  script:
    - cd ../Application/ChooseYourAdventure
    - gradle test
